### PR TITLE
Trivial fixes for xbmc.log under python2

### PR DESCRIPTION
**Pull request by enen92**
Hey montelesse,

I am one of those patiently waiting to get this feature on Kodi master. I gave it a try with your last build since I configured plex recently. Unfortunately I was not able to use the addon right away due to exceptions being triggered in your log function (hopefully when python3 is included all this unicode crap can finally go away). In this PR I send the changes I needed to make to have it working.

A few random notes I found while testing (since I don't know if some are known issues):

- I found it really easy to configure. My server was detected right away and I was able to import to the kodi database. 
- Items were marked as watched in plex server when I marked them as watched in kodi.
- Subtitles were not available to the player although the item contains subtitles in plex server
- Scroble/watch times were not synchronised to plex server.
- Rebasing on a version with python3 would be really nice. If you need help porting the addons just ping me.

Thanks a lot for your hard work on this!

### CODE REVIEW

**Comment by Montellese** [comment]
Thanks a lot for your support and feedback. As you may have noticed from the code I'm not a python developer so any support is welcome.

I'll apply the same changes to the `mediaimporter.emby` add-on because it shares the utils logic.

Concerning your notes on testing:
* most feedback has been reported at https://forum.kodi.tv/showthread.php?tid=224794 and any additional feedback (success or failure) is very welcome.
* I have not tested subtitles yet. Especially external subtitles usually need a lot of hacking to get working in Kodi. This has also been reported for imports from Emby.
* I did not find a way to update last played or resume point on a Plex server. I only found an API for marking items as watched / unwatched. Any pointers are welcome.
* Rebasing my branch on current master for Python 3 support is the next big task I'll have to tackle. I didn't do it yet because my old dev machine was still on Windows 7 which is not supported anymore by Kodi Matrix.

**Review by Montellese — APPROVED** [review]

**Comment by Montellese** [comment]
I've applied the same changes to `mediaimporter.emby`, see https://github.com/Montellese/mediaimporter.emby/commit/93ed8e02646cb046c86da68fb7cf09512d21c2f9.

**Comment by enen92** [comment]
> * I did not find a way to update last played or resume point on a Plex server. I only found an API for marking items as watched / unwatched. Any pointers are welcome.

Did some investigation using the plex webapp and also the official plex kodi addon and it looks like they use the same API. Wrote a sample example about how it works. Basically you need to send the player state and time continuously to the server (webapp does it every 8 secs; plex kodi addon does it every second) and also emit events on several player states. That's the reason I keep a thread reporting it each 8 secs. Code below simulates a player, you need to provide:

- Your token
- The id (key) of your library item
- The duration of the item

```python
import requests
import time
import threading

URL = 'http://127.0.0.1:32400/:/timeline'

PLEX_TOKEN = 'your_token'

HEADERS = {
    'X-Plex-Token': PLEX_TOKEN,
    'Accept-Encoding': 'gzip,deflate',
    'User-Agent': 'Fake-Plex-Request/0.1.6 Kodi/19.0-ALPHA1-Git:20191228-149e1d4b59 CPython/2.7.15 Darwin/19.0.0',
    'X-Plex-Device': 'OSX',
    'X-Plex-Product': 'Montelesse test',
    'X-Plex-Version': '0.1.6',
    'X-Plex-Device-Name': 'Kodi Add-on (enen-air.home)',
    'X-Plex-Platform': 'Kodi',
    'X-Plex-Model': 'Unknown',
    'X-Plex-Platform-Version': '19.0-ALPHA1 Git:20191228-149e1d4b59',
    'X-Plex-Client-Identifier': 'my-kodi',
    'X-Plex-Client-Capabilities': 'timeline,playback,navigation',
    'X-Plex-Session-Identifier': str(time.time()),
}

class PlaybackSession:

    def __init__(self, item):
        self.__session = requests.Session() # create a new session
        # fake item
        self.__item = item
        # time
        self.__current_time = 0
        self.__current_state = None
        # init reporting thread
        self.__reporting = False
        self.__initial_timestamp = time.time()
        self.__reportStateThread = threading.Thread(target=self.__reporting_loop)
        # start reporting
        self.__reportStateThread.start()

    def __reporting_loop(self):
        print("Reporting loop started...")
        self.__reporting = True
        while time.time() - self.__initial_timestamp < 90 and self.__reporting: # only execute for 90 seconds
            if self.__current_state:
                self.__reportPlaybackState()

            time.sleep(8)
            if self.__current_state == 'playing':
                self.__current_time = 8*1000 + self.__current_time

    def __reportPlaybackState(self):
        req = self.__session.get(
            URL,
            params = {
                'state': self.__current_state,
                'key': '/library/metadata/%s' % self.__item['key'],
                'time': str(self.__current_time),
                'duration': str(self.__item['duration']),
                'ratingKey': self.__item['key'],
            },
            headers = HEADERS
        )

    def playbackStarted(self):
        print("Playback started")
        self.__current_time = 0
        self.__current_state = 'playing'
        self.__reportPlaybackState()

    def seek(self, percentage):
        print("Seek to %s" % str(int(percentage * self.__item['duration'])))
        self.__current_time = int(percentage * self.__item['duration'])
        self.__reportPlaybackState()

    def pause(self):
        print("Pausing...")
        self.__current_state = 'paused'
        self.__reportPlaybackState()

    def resume(self):
        print("Resuming....")
        self.__current_state = 'playing'
        self.__reportPlaybackState()

    def stop(self):
        print("Stopping....")
        self.__current_state = 'stopped'
        self.__reportPlaybackState()
        self.__end()


    def __end(self):
        print("Waiting for reporting thread to die")
        self.__reporting = False
        self.__reportStateThread.join()


if __name__ == '__main__':
    virtual_item = {
        'key': '14', # key identifier in plex for the item being played
        'duration': 7130000 # item duration
    }
    # Initialize playback
    player = PlaybackSession(virtual_item)
    try:
        # Start playback
        player.playbackStarted()
        # let the item play for 20 seconds and pause
        time.sleep(20)
        player.pause()
        # let it stay paused for 10 seconds and resume
        time.sleep(10)
        player.resume()
        # let it play for 5 seconds and seek to 25%
        time.sleep(5)
        player.seek(0.25)
        # let it play for 40 secs and stop playback
        time.sleep(20)
        player.stop()
    except KeyboardInterrupt:
        player.stop()

```

It looks like apart from this REST API there is also a way to subscribe to events emitted by the server. Those events as far as I understood may enable you to sync the watched playback time (timeline) for the items in kodi if they are watched somewhere else. 
Is any of this possible right now? I mean...a service extension point in the addon would allow to subscribe the events but, can we feed that info into kodi so that the watched state is reflected on the database?

I might take a stab at implementing the player part of the addon. For now this was just investigation :)
Keep up the great work

**Comment by Montellese** [comment]
@enen92 thanks a lot for the detailed description and example. I'm actually doing something very similar in the Emby mediaimporter, see https://github.com/Montellese/mediaimporter.emby/blob/master/observer.py#L24 and https://github.com/Montellese/mediaimporter.emby/blob/master/emby/player.py. I guess I'll have to implement something similar for Plex.

**Comment by Montellese** [comment]
I've created a new issue #2 to be able to discuss this since it has nothing to do with this PR. Feel free to create more issues / bugs for other things you've noticed (like subtitles not working).

**Comment by enen92** [comment]
Yeap I saw your emby player implementation. For plex the aproach would be quite similar.

My question was more the other way around though. I was wondering how we could update the watched time on kodi if the item is watched in some other client. Is there any mediaimport interface for that?

**Comment by Montellese** [comment]
Yes and it's already partially implemented, see `observer.py` and `plex/provider_observer.py`.

**Pull request merged**
